"""Per-provider projection logic.

Each target knows how to take the canonical assets (the text of ``AGENTS.md`` and
the parsed list of skills) and write the files the corresponding agent reads.

The two persistent-rule mechanisms in 2026 have converged on:
  * ``AGENTS.md``  — open standard, read natively by Codex, Cursor, Copilot, ...
  * ``CLAUDE.md``  — Claude Code's file (supports ``@import``)
and skills converge on ``SKILL.md`` (Claude Code and Codex share the format).
This module encodes those facts so the CLI can stay declarative.
"""

from __future__ import annotations

import json
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, List

# ---------------------------------------------------------------------------
# Shared data
# ---------------------------------------------------------------------------

MCP_SERVER_NAME = "openproblems-spatial"
MCP_COMMAND = "openproblems-mcp-server"

GENERATED_BANNER = (
    "<!-- GENERATED by installer/ from AGENTS.md + skills/. Do not edit by hand; "
    "edit AGENTS.md / skills/ and re-run `spatialai-install`. -->\n\n"
)


@dataclass
class Skill:
    """A parsed SKILL.md: name, description, and the full source path."""

    name: str
    description: str
    path: Path
    body: str = ""


@dataclass
class Sources:
    """The canonical assets the installer reads."""

    repo_root: Path
    agents_md: str
    skills: List[Skill] = field(default_factory=list)


def _mcp_json() -> str:
    """The standard JSON MCP config used by Claude Code and Cursor."""
    return (
        json.dumps(
            {
                "mcpServers": {
                    MCP_SERVER_NAME: {
                        "command": MCP_COMMAND,
                        "args": [],
                        "env": {"OPENPROBLEMS_MCP_LOG_LEVEL": "INFO"},
                    }
                }
            },
            indent=2,
        )
        + "\n"
    )


def _mcp_toml() -> str:
    """The TOML MCP config snippet used by Codex (``~/.codex/config.toml``)."""
    return (
        f"[mcp_servers.{MCP_SERVER_NAME}]\n"
        f'command = "{MCP_COMMAND}"\n'
        f"args = []\n"
        f'env = {{ OPENPROBLEMS_MCP_LOG_LEVEL = "INFO" }}\n'
    )


def _write(path: Path, content: str, written: List[Path]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    written.append(path)


def _copy_skill(skill: Skill, dest_dir: Path, written: List[Path]) -> None:
    """Copy a skill's SKILL.md into ``dest_dir/<name>/SKILL.md``."""
    dest = dest_dir / skill.name / "SKILL.md"
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(skill.path, dest)
    written.append(dest)


# ---------------------------------------------------------------------------
# Target implementations
# ---------------------------------------------------------------------------


def install_claude(src: Sources, dest: Path, written: List[Path]) -> None:
    """Claude Code: CLAUDE.md pointer, .claude/skills/, .mcp.json."""
    claude_md = (
        GENERATED_BANNER
        + "# CLAUDE.md\n\n"
        + "This project's canonical, provider-neutral instructions live in "
        + "[`AGENTS.md`](./AGENTS.md). Read it first.\n\n"
        + "@AGENTS.md\n\n"
        + "## Claude Code notes\n\n"
        + "- Skills are installed under `.claude/skills/` and load on demand.\n"
        + "- The MCP server is configured in `.mcp.json` "
        + f"(server name `{MCP_SERVER_NAME}`).\n"
    )
    _write(dest / "CLAUDE.md", claude_md, written)
    for skill in src.skills:
        _copy_skill(skill, dest / ".claude" / "skills", written)
    _write(dest / ".mcp.json", _mcp_json(), written)


def install_codex(src: Sources, dest: Path, written: List[Path]) -> None:
    """OpenAI Codex: reads AGENTS.md natively; install skills + MCP TOML snippet."""
    # AGENTS.md is read natively by Codex; ensure it exists at the destination.
    if dest.resolve() != src.repo_root.resolve():
        _write(dest / "AGENTS.md", src.agents_md, written)
    for skill in src.skills:
        _copy_skill(skill, dest / ".codex" / "skills", written)
    _write(
        dest / ".codex" / "mcp-config.toml",
        "# Append to ~/.codex/config.toml to register the MCP server.\n" + _mcp_toml(),
        written,
    )


def install_cursor(src: Sources, dest: Path, written: List[Path]) -> None:
    """Cursor: .cursor/rules/*.mdc (self-contained) and .cursor/mcp.json."""
    rules_dir = dest / ".cursor" / "rules"
    # Main always-applied rule embeds AGENTS.md (Cursor has no @import).
    main_rule = (
        "---\n"
        "description: OpenProblems spatial transcriptomics co-pilot — project rules\n"
        "alwaysApply: true\n"
        "---\n\n" + GENERATED_BANNER + src.agents_md
    )
    _write(rules_dir / "openproblems.mdc", main_rule, written)
    # One on-demand rule per skill (description-gated, not always applied).
    for skill in src.skills:
        rule = (
            "---\n"
            f"description: {skill.description}\n"
            "alwaysApply: false\n"
            "---\n\n" + GENERATED_BANNER + skill.body
        )
        _write(rules_dir / f"{skill.name}.mdc", rule, written)
    _write(dest / ".cursor" / "mcp.json", _mcp_json(), written)


def _self_contained_md(src: Sources) -> str:
    """AGENTS.md plus the FULL skill bodies, for agents with no skill auto-load.

    Embedding the bodies (not just an index) ensures the model actually has the
    playbooks in context — agents like Copilot, Gemini CLI, and Antigravity CLI
    won't autonomously open the SKILL.md files otherwise.
    """
    parts = [GENERATED_BANNER, src.agents_md, "\n\n# Skill playbooks\n"]
    parts.append("\nLoad the one matching your task; full text follows.\n")
    for s in src.skills:
        parts.append(f"\n---\n\n<!-- skill: {s.name} -->\n{s.body.strip()}\n")
    return "".join(parts)


def install_copilot(src: Sources, dest: Path, written: List[Path]) -> None:
    """GitHub Copilot: .github/copilot-instructions.md (self-contained)."""
    _write(
        dest / ".github" / "copilot-instructions.md",
        _self_contained_md(src),
        written,
    )


def install_gemini(src: Sources, dest: Path, written: List[Path]) -> None:
    """Gemini CLI: GEMINI.md context file (self-contained) + .gemini/settings.json."""
    _write(dest / "GEMINI.md", _self_contained_md(src), written)
    # Gemini CLI reads MCP servers from .gemini/settings.json; the top-level
    # mcpServers shape matches the standard JSON config we emit elsewhere.
    _write(dest / ".gemini" / "settings.json", _mcp_json(), written)


def install_antigravity(src: Sources, dest: Path, written: List[Path]) -> None:
    """Google Antigravity CLI (agy): AGENTS.md + embedded skills + .agents/ config.

    Antigravity reads ``AGENTS.md`` natively and a ``.agents/`` workspace dir.
    We also write a self-contained context file with full skill bodies (the CLI
    won't open SKILL.md files on its own) and the MCP config it reads from
    ``.agents/mcp_config.json``.
    """
    if dest.resolve() != src.repo_root.resolve():
        _write(dest / "AGENTS.md", src.agents_md, written)
    for skill in src.skills:
        _copy_skill(skill, dest / ".agents" / "skills", written)
    _write(dest / ".agents" / "context.md", _self_contained_md(src), written)
    _write(dest / ".agents" / "mcp_config.json", _mcp_json(), written)


@dataclass
class Target:
    key: str
    label: str
    install: Callable[[Sources, Path, List[Path]], None]


TARGETS = {
    "claude": Target("claude", "Claude Code", install_claude),
    "codex": Target("codex", "OpenAI Codex", install_codex),
    "cursor": Target("cursor", "Cursor", install_cursor),
    "copilot": Target("copilot", "GitHub Copilot", install_copilot),
    "gemini": Target("gemini", "Gemini CLI (legacy)", install_gemini),
    "antigravity": Target("antigravity", "Google Antigravity CLI", install_antigravity),
}
